export const actionTypes = {
  SET_FORM_VALUES: "SET_FORM_VALUES",
  CREATE_INTERVIEW_START: "CREATE_INTERVIEW_START",
  CREATE_INTERVIEW_SUCCESS: "CREATE_INTERVIEW_SUCCESS",
};

export const userConstants = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USER_LOGOUT",
};
